import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a className={styles.nextjslink} href='https://nextjs.org/docs/getting-started'>Next.js!</a>
        </h1>
        <p className={styles.description}>Get started by editing {""}
        <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.Card_container} >
          <a className={styles.card} href='https://nextjs.org/docs/getting-started'>
            <h2>Documentation &rarr;</h2>
            <p>Find in depth information about Next.js features and API. &#128516;</p>
          </a>
          <a className={styles.card} href='https://nextjs.org/learn/foundations/about-nextjs?utm_source=next-site&utm_medium=nav-cta&utm_campaign=next-website'>
            <h2>learn &rarr;</h2>
            <p>Learn about Next.js in an interactive courses and quizzes &#128525;</p>
          </a>
          <a className={styles.card} href='https://nextjs.org/examples'>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects. &#128512;</p>
          </a>
          <a className={styles.card} href='https://nextjs.org/examples'>
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel. &#128151;</p>
          </a>
        </div>
       
      </main>
       <footer className={styles.footer}>
        <a href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"target="_blank"rel="noopener noreferrer"'>
          Powered by{''}
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </a>
       </footer> 
    </div>
  )
}

export default Home
